### ISSUE TITLE
Re-install not working after reboot, Mac OS 10.9.5

### ISSUE THREAD

**Issue by johnnyutahh** [szhu/fix-growlvoice#11]
I've rebooted and re-installed this solution several times, but on the latest reboot and re-install, it's not working. Details here:  http://apple.stackexchange.com/q/189576/13179

Thoughts?

**Comment by szhu** [comment]
I have a feeling Google completely dropped the API recently, since this error message you're getting `"Sign in error: The operation couldn't be completed. (com.google.HTTPStatus error 404.)` is unlike the previous one about JSON errors.

I can't test this myself anymore because I opted to use Voice through Hangouts, which prevents Voice from going to Voice.

**Comment by johnnyutahh** [comment]
Thanks szhu. Has anybody else recently used GrowlVoice successfully? Specifically, have you attempt a Google-Voice account re-login?

**Comment by johnnyutahh** [comment]
It looks like Google may have broken the API used by GrowlVoice:
http://apple.stackexchange.com/a/189766/13179

**Comment by mralexgray** [comment]
FUCK.  This SUCKS.  Google is such an ASSHOLE, sometimes.

**Comment by szhu** [comment]
I think this is simply an issue of Google not reaping any profits from Voice. (pure speculation btw)

**Comment by mralexgray** [comment]
Well - then they should have come to grips with that BEFORE they offered a product on which people depend on - to which they constantly REMOVE features and interoperability.

**Comment by mralexgray** [comment]
why is this closed?  people are so OCD.. if the problem is at all hard.. they'd rather close it than see an open issue.  whatever, lol.

**Comment by szhu** [comment]
This is technically a "won't fix" so that's why it was closed, but I will go ahead and open a new, more generic issue stating that this is no longer working.

**Comment by szhu** [comment]
Superseded by #12.
